language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - "8"
install:
  - yarn install
  - cd react
  - yarn install
  - cd ..
script:
  - yarn lint:locales
  - cd react
  - yarn test
